language: python
python:
  - "2.7"

env:
  - ADMIN_PARTY=true

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - curl -X PUT localhost:5984/test

# command to run tests
script: nosetests

after_success:
  - codecov

services:
  - couchdb
